name: Dispatch
description: 'Dispatches a payload when a commit is made to repository for automation'

on: [push]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PA_TOKEN }}
          repository: m-ama/NeuroDock
          event-type: my-event
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}
